---
ngircd_channels: []
ngircd_global_adminemail: ngircd@localhost
ngircd_global_admininfo1: ngircd
ngircd_global_admininfo2: localhost
ngircd_global_helpfile: /usr/share/doc/ngircd/Commands.txt
ngircd_global_info: localhost
ngircd_global_listen: 0.0.0.0
ngircd_global_name: localhost
ngircd_global_network: localnet
ngircd_global_pidfile: /var/run/ngircd/ngircd.pid
ngircd_global_servergid: ngircd
ngircd_global_serveruid: ngircd
ngircd_limits_connectretry: 60
ngircd_limits_idletimeout: 0
ngircd_limits_maxconnections: 0
ngircd_limits_maxconnectionsip: 5
ngircd_limits_maxjoins: 10
ngircd_limits_maxnicklength: 9
ngircd_limits_maxlistsize: 100
ngircd_limits_pingtimeout: 120
ngircd_limits_pongtimeout: 20
ngircd_operators: []
ngircd_options_allowedchanneltypes: '#&+'
ngircd_options_allowremoteoper: false
ngircd_options_connectipv6: true
ngircd_options_connectipv4: true
ngircd_options_defaultusermodes: i
ngircd_options_dns: true
ngircd_options_ident: true
ngircd_options_moreprivacy: false
ngircd_options_noticebeforeregistration: false
ngircd_options_opercanusemode: false
ngircd_options_operchanpautoop: true
ngircd_options_operservermode: false
ngircd_options_pam: true
ngircd_options_pamisoptional: false
ngircd_options_requireauthping: false
ngircd_options_scrubctcp: false
ngircd_options_syslogfacility: local5
ngircd_servers: []
ngircd_ssl: false
...
